language: erlang
script:
     - "./rebar compile && ./rebar skip_deps=true eunit"
     - ./run-dialyzer.sh
notifications:
  email: marcelloceschia@users.sourceforge.net
otp_release:
     - 19.0
     - 18.3
     - 18.2.1
     - 18.1
     - 18.0
     - 17.1
     - 17.0
     - R16B03-1
     - R16B02
     - R16B01
     - R15B03
     - R15B02
     - R15B01
